CREATE TABLE "cliente" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"unit_code" text,
	"status_contrato" text,
	"nome_completo" text NOT NULL,
	"cpf_cnpj" text,
	"nascimento" text,
	"nacionalidade" text,
	"estado_civil" text,
	"endereco" text,
	"cidade_estado" text,
	"cep" text,
	"email_principal" text,
	"email_secundario" text,
	"celular" text,
	"telefone" text,
	"banco_financ" text,
	"renda_bruta" numeric(15, 2),
	"renda_liquida" numeric(15, 2),
	"comprometimento" text,
	"possui_fgts" text,
	"saldo_fgts" numeric(15, 2),
	"score_credito" integer,
	"restricoes" text,
	"morar_ou_investir" text,
	"ramo_atividade" text,
	"cargo_funcao" text,
	"area_atuacao" text,
	"empresa" text,
	"regime_trabalho" text,
	"local_trabalho" text,
	"tempo_empresa" text,
	"possui_imovel" text,
	"motivacao_compra" text,
	"como_conheceu" text,
	"indicado_por" text,
	"interesse" integer,
	"obs_estrategicas" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "cliente" ADD CONSTRAINT "cliente_tenant_id_tenant_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenant"("id") ON DELETE cascade ON UPDATE no action;